version: '3'

services:

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin.local
      MYSQL_DATABASE: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
    networks:
      - dataflow
    volumes:
      - db_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --explicit_defaults_for_timestamp=1

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - dataflow
    deploy:
      restart_policy:
        condition: on-failure

  web: &web
    build: .
    image: ziwon/airflow-boilerplate
    ports:
      - "8080:8080"
    restart: on-failure:3
    networks:
      - dataflow
    command: web

  scheduler:
    <<: *web
    ports: []
    command: scheduler

  worker:
    <<: *web
    ports:
      - "8793:8793"
    command: worker

  flower:
    <<: *web
    ports:
      - "5555:5555"
    command: flower

networks:
  dataflow:

volumes:
  db_data: